use std::ffi::CStr;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BinParamType {
    F32,
    Color3,
    Action,
    String,
}

#[derive(Clone, Copy, Debug)]
pub struct BinParamSpec {
    pub id: &'static CStr,
    pub label: &'static CStr,
    pub group: &'static CStr,
    pub param_type: BinParamType,
    pub min_value: f32,
    pub max_value: f32,
    pub default_value: f32,
    pub flags: u32,
}

impl BinParamSpec {
    pub fn id_str(&self) -> &'static str {
        self.id.to_str().unwrap_or("")
    }

    pub fn label_str(&self) -> &'static str {
        self.label.to_str().unwrap_or("")
    }

    pub fn group_str(&self) -> &'static str {
        self.group.to_str().unwrap_or("")
    }
}

macro_rules! cstr {
    ($value:literal) => {
        unsafe { CStr::from_bytes_with_nul_unchecked(concat!($value, "\0").as_bytes()) }
    };
}

macro_rules! f32_param {
    ($id:literal, $label:literal, $group:literal, $min:expr, $max:expr, $default:expr) => {
        BinParamSpec {
            id: cstr!($id),
            label: cstr!($label),
            group: cstr!($group),
            param_type: BinParamType::F32,
            min_value: $min,
            max_value: $max,
            default_value: $default,
            flags: 0,
        }
    };
}

macro_rules! color3_param {
    ($id:literal, $label:literal, $group:literal, $min:expr, $max:expr, $default:expr) => {
        BinParamSpec {
            id: cstr!($id),
            label: cstr!($label),
            group: cstr!($group),
            param_type: BinParamType::Color3,
            min_value: $min,
            max_value: $max,
            default_value: $default,
            flags: 0,
        }
    };
}

macro_rules! action_param {
    ($id:literal, $label:literal, $group:literal) => {
        BinParamSpec {
            id: cstr!($id),
            label: cstr!($label),
            group: cstr!($group),
            param_type: BinParamType::Action,
            min_value: 0.0,
            max_value: 1.0,
            default_value: 0.0,
            flags: 1,
        }
    };
}

macro_rules! string_param {
    ($id:literal, $label:literal, $group:literal) => {
        BinParamSpec {
            id: cstr!($id),
            label: cstr!($label),
            group: cstr!($group),
            param_type: BinParamType::String,
            min_value: 0.0,
            max_value: 1.0,
            default_value: 0.0,
            flags: 0,
        }
    };
}

pub const ROTO_PARAMS: &[BinParamSpec] = &[
    f32_param!("square_size", "Square Size", "Parameters", 0.05, 0.5, 0.2),
    f32_param!("circle_radius", "Circle Radius", "Parameters", 0.05, 0.2, 0.11),
    f32_param!("edge_thickness", "Edge Thickness", "Parameters", 0.001, 0.01, 0.003),
    f32_param!("animation_speed", "Animation Speed", "Parameters", 1.0, 30.0, 12.0),
    color3_param!("background_color", "Background Color", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("edge_color_intensity", "Edge Brightness", "Parameters", 0.1, 2.0, 1.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const NEURON2D_PARAMS: &[BinParamSpec] = &[
    f32_param!("pixel_offset", "Pixel Offset Y", "Neuron Parameters", -3.14, 3.14, -1.0),
    f32_param!("pixel_offset2", "Pixel Offset X", "Neuron Parameters", -3.14, 3.14, 1.0),
    f32_param!("lights", "Lights", "Neuron Parameters", 0.0, 12.2, 2.2),
    f32_param!("exp", "Exp", "Neuron Parameters", 1.0, 120.0, 4.0),
    f32_param!("frame", "Frame", "Visual Settings", 0.0, 5.2, 1.0),
    f32_param!("col1", "Iterations", "Visual Settings", 0.0, 150.0, 100.0),
    f32_param!("col2", "Color 2", "Visual Settings", 0.0, 20.0, 1.0),
    f32_param!("decay", "Feedback", "Visual Settings", 0.0, 1.0, 1.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const AUDIOVIS_PARAMS: &[BinParamSpec] = &[
    f32_param!("red_power", "Red Power", "Visual Parameters", 0.1, 2.0, 0.5),
    f32_param!("green_power", "Green Power", "Visual Parameters", 0.1, 2.0, 0.5),
    f32_param!("blue_power", "Blue Power", "Visual Parameters", 0.1, 2.0, 0.5),
    f32_param!("green_boost", "Green Boost", "Visual Parameters", 0.0, 3.0, 0.5),
    f32_param!("contrast", "Contrast", "Visual Parameters", 0.1, 3.0, 0.5),
    f32_param!("gamma", "Gamma", "Visual Parameters", 0.1, 3.0, 0.5),
    f32_param!("glow", "Glow", "Visual Parameters", 0.0, 1.0, 0.5),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const BLOCKGAME_PARAMS: &[BinParamSpec] = &[
    f32_param!("block_x", "Block X", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("block_y", "Block Y", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("block_z", "Block Z", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("block_width", "Block Width", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("block_height", "Block Height", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("block_depth", "Block Depth", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("movement_speed", "Movement Speed", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("movement_range", "Movement Range", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("camera_height", "Camera Height", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("camera_angle", "Camera Angle", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("camera_scale", "Camera Scale", "Parameters", 0.0, 1.0, 0.5),
];

pub const BUDDHABROT_PARAMS: &[BinParamSpec] = &[
    f32_param!("escape_radius", "Escape Radius", "Fractal", 2.0, 20.0, 4.0),
    f32_param!("zoom", "Zoom", "View", 0.1, 10.0, 0.5),
    f32_param!("offset_x", "Offset X", "View", -2.0, 1.0, -0.5),
    f32_param!("offset_y", "Offset Y", "View", -1.5, 1.5, 0.0),
    f32_param!("rotation", "Rotation", "View", -3.14159, 3.14159, 1.55),
    f32_param!("exposure", "Exposure", "Tone Mapping", 0.5, 10.0, 6.5),
    f32_param!("sample_density", "Sample Density", "Fractal", 0.1, 2.0, 0.5),
    f32_param!("motion_speed", "Motion (clears buf)", "Rendering", 0.0, 1.0, 0.0),
    f32_param!("dithering", "Dithering", "Tone Mapping", 0.0, 1.0, 0.2),
    f32_param!("wavelength_min", "Wavelength Min", "Parameters", 0.0, 1.0, 485.0),
    f32_param!("wavelength_max", "Wavelength Max", "Parameters", 0.0, 1.0, 660.0),
    f32_param!("gamma", "Gamma", "Tone Mapping", 0.2, 2.2, 0.6),
    f32_param!("saturation", "Saturation", "Spectral", 0.0, 3.0, 1.2),
    f32_param!("color_shift", "Color Curve", "Spectral", 0.0, 2.0, 1.1),
    f32_param!("intensity_scale", "Intensity", "Spectral", 0.1, 10.0, 5.0),
    f32_param!("white_balance_r", "R", "Tone Mapping", 0.5, 2.0, 1.2),
    f32_param!("white_balance_g", "G", "Tone Mapping", 0.5, 2.0, 1.0),
    f32_param!("white_balance_b", "B", "Tone Mapping", 0.5, 2.0, 1.08),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const CLIFFORDCOMPUTE_PARAMS: &[BinParamSpec] = &[
    f32_param!("a", "Parameter A", "Attractor Parameters", -3.0, 3.0, 1.7),
    f32_param!("b", "Parameter B", "Attractor Parameters", -3.0, 3.0, 1.7),
    f32_param!("c", "Parameter C", "Attractor Parameters", -3.0, 3.0, 0.6),
    f32_param!("d", "Parameter D", "Attractor Parameters", -3.0, 3.0, 1.2),
    f32_param!("motion_speed", "Animation Speed", "Visual Settings", 0.0, 3.0, 1.0),
    f32_param!("rotation_x", "Rotation X", "Visual Settings", -1.0, 1.0, 0.0),
    f32_param!("rotation_y", "Rotation Y", "Visual Settings", -1.0, 1.0, 0.0),
    f32_param!("brightness", "Brightness", "Visual Settings", 0.00001, 0.0001, 0.00004),
    f32_param!("color1_r", "Color1 R", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("color1_g", "Color1 G", "Parameters", 0.0, 1.0, 0.7),
    f32_param!("color1_b", "Color1 B", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color2_r", "Color2 R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color2_g", "Color2 G", "Parameters", 0.0, 1.0, 0.3),
    f32_param!("color2_b", "Color2 B", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("scale", "Attractor Scale", "Visual Settings", 0.1, 2.0, 0.6),
    f32_param!("dof_amount", "DOF Amount", "Depth of Field", 0.0, 3.0, 1.0),
    f32_param!("dof_focal_dist", "Focal Distance", "Depth of Field", 0.0, 1.0, 0.5),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const CNN_PARAMS: &[BinParamSpec] = &[
    f32_param!("brush_size", "Brush Size", "Brush", 0.001, 0.015, 0.5),
    f32_param!("input_resolution", "Input Resolution", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("feature_maps_1", "Feature Maps 1", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("feature_maps_2", "Feature Maps 2", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("num_classes", "Num Classes", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("normalization_mean", "Normalization Mean", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("normalization_std", "Normalization Std", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("conv1_pool_size", "Conv1 Pool Size", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("conv2_pool_size", "Conv2 Pool Size", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const COMPUTECOLORS_PARAMS: &[BinParamSpec] = &[
    f32_param!("animation_speed", "Speed", "Effects", 0.0, 3.0, 1.0),
    f32_param!("splat_size", "Splat Size", "Particles", 0.1, 2.0, 0.8),
    f32_param!("particle_spread", "Scramble Amount", "Effects", 0.0, 1.0, 0.0),
    f32_param!("intensity", "Intensity", "Particles", 0.1, 6.0, 2.0),
    f32_param!("particle_density", "Density", "Particles", 0.1, 1.0, 0.4),
    f32_param!("brightness", "Brightness", "Particles", 36.0, 48.0, 36.0),
    f32_param!("physics_strength", "Return Force", "Effects", 0.0, 12.0, 0.5),
    f32_param!("trail_length", "Trail Length", "Flow Trails", 0.0, 2.0, 0.0),
    f32_param!("trail_decay", "Trail Decay", "Flow Trails", 0.8, 1.0, 0.95),
    f32_param!("flow_strength", "Flow Strength", "Flow Trails", 0.0, 3.0, 1.0),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const CUNEUS_PARAMS: &[BinParamSpec] = &[
    f32_param!("background_color", "Background", "Colors", 0.0, 1.0, 0.4),
    color3_param!("hue_color", "Hue Color", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("light_intensity", "Light Intensity", "Lighting", 0.0, 3.2, 1.8),
    f32_param!("rim_power", "Rim Power", "Lighting", 0.1, 10.0, 3.0),
    f32_param!("ao_strength", "AO Strength", "Lighting", 0.0, 10.0, 0.1),
    f32_param!("env_light_strength", "Env Light Strength", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("iridescence_power", "Iridescence", "Effects", 0.0, 1.0, 0.2),
    f32_param!("falloff_distance", "Light Falloff", "Effects", 0.5, 5.0, 1.0),
    f32_param!("global_light", "Global Light", "Lighting", 0.1, 2.0, 1.0),
    f32_param!("alpha_threshold", "Alpha Threshold", "Effects", 0.0, 3.0, 1.0),
    f32_param!("mix_factor_scale", "Mix Factor Scale", "Effects", 0.0, 1.5, 0.3),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const DEBUGSCREEN_PARAMS: &[BinParamSpec] = &[
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const FFT_PARAMS: &[BinParamSpec] = &[
    f32_param!("filter_strength", "Filter Strength", "Filter Settings", 0.0, 1.0, 0.3),
    f32_param!("filter_direction", "Filter Direction", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("filter_radius", "Filter Radius", "Parameters", 0.0, 1.0, 3.0),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const FLUID_PARAMS: &[BinParamSpec] = &[
    f32_param!("viscosity", "Viscosity", "Flow", 0.0, 1.0, 0.03),
    f32_param!("gravity", "Gravity", "Physics", 0.0, 0.2, 0.002),
    f32_param!("pressure_scale", "Pressure", "Physics", 0.0, 2.0, 1.0),
    f32_param!("vortex_strength", "Confinement", "Vortices", 0.0, 1.0, 0.18),
    f32_param!("turbulence", "Dissipation", "Flow", 0.0, 0.01, 0.0005),
    f32_param!("flow_speed", "Speed", "Flow", 0.1, 5.0, 2.0),
    f32_param!("pos_diffusion", "Smoothing", "Physics", 0.0, 1.0, 0.3),
    f32_param!("texture_influence", "Buoyancy", "Physics", 0.0, 2.0, 1.3),
    f32_param!("light_intensity", "Light", "Display", 0.3, 3.0, 1.3),
    f32_param!("spec_power", "Spec Sharpness", "Display", 4.0, 128.0, 36.0),
    f32_param!("spec_intensity", "Spec Intensity", "Display", 0.0, 5.0, 2.0),
    f32_param!("color_vibrancy", "Saturation", "Display", 0.5, 2.5, 1.3),
    f32_param!("vortex_radius", "Radius", "Vortices", 0.001, 0.05, 0.006),
    f32_param!("gamma", "Gamma", "Display", 0.5, 2.5, 1.1),
    f32_param!("feedback", "Feedback", "Flow", 0.0, 1.0, 0.93),
    f32_param!("vortex_speed", "Speed", "Vortices", 0.005, 0.15, 0.03),
    f32_param!("force_mode", "Spread", "Glow", 0.0, 1.0, 0.5),
    f32_param!("force_harmony", "Softness", "Vortices", 0.0, 2.0, 0.5),
    f32_param!("force_count", "Sources", "Vortices", 0.0, 18.0, 6.0),
    f32_param!("contrast", "Contrast", "Display", 0.0, 0.8, 0.15),
    f32_param!("warp_amount", "Warp", "Distortion", 0.5, 5.0, 1.0),
    f32_param!("flow_intensity", "Flow Intensity", "Distortion", 0.5, 5.0, 1.0),
    f32_param!("color_advect", "Color Advect", "Distortion", 0.0, 3.0, 1.0),
    f32_param!("drift_decay", "Drift Decay", "Distortion", 0.0, 0.05, 0.0),
    f32_param!("dye_intensity", "Intensity", "Glow", 0.0, 2.0, 0.8),
    f32_param!("dye_radius", "Source Tint", "Glow", 0.1, 5.0, 1.5),
    f32_param!("bg_boil", "Noise", "Flow", 0.0, 1.0, 0.15),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const GAUSSIAN_PARAMS: &[BinParamSpec] = &[
    f32_param!("learning_rate", "pos LR", "Training", 0.0001, 0.1, 0.5),
    f32_param!("color_learning_rate", "Color Learning Rate", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("temperature", "temp", "Training", 0.1, 5.0, 0.5),
    f32_param!("error_scale", "Error Scale", "vis", 0.5, 10.0, 0.5),
    f32_param!("min_sigma", "Min Sigma", "Advanced", 0.001, 0.05, 0.5),
    f32_param!("max_sigma", "Max Sigma", "Advanced", 0.02, 0.3, 0.5),
    f32_param!("position_noise", "Position", "Advanced", 0.0, 1.0, 0.5),
    f32_param!("sigma_learning_rate", "Sigma Learning Rate", "Parameters", 0.0, 1.0, 0.5),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const GAUSSIAN3D_PARAMS: &[BinParamSpec] = &[
    f32_param!("gaussian_size", "Gaussian Size", "Visual Settings", 0.1, 2.0, 0.5),
    f32_param!("scene_scale", "Scene Scale", "Visual Settings", 0.01, 100.0, 0.5),
    f32_param!("gamma", "Gamma", "Visual Settings", 0.1, 2.2, 0.5),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const JFA_PARAMS: &[BinParamSpec] = &[
    f32_param!("a", "a", "Clifford Attractor", -5.0, 5.0, -2.7),
    f32_param!("b", "b", "Clifford Attractor", -5.0, 5.0, 0.7),
    f32_param!("c", "c", "Clifford Attractor", -5.0, 5.0, 0.2),
    f32_param!("d", "d", "Clifford Attractor", -5.0, 5.0, 0.2),
    f32_param!("scale", "Scale", "Clifford Attractor", 0.1, 1.0, 0.3),
    f32_param!("n", "Pattern Speed (N)", "JFA Parameters", 0.01, 1.0, 0.1),
    f32_param!("gamma", "Gamma", "Colors", 0.1, 4.0, 2.1),
    f32_param!("color_intensity", "Color Intensity", "Colors", 0.1, 3.0, 1.0),
    f32_param!("color_r", "Color R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color_g", "Color G", "Parameters", 0.0, 1.0, 2.0),
    f32_param!("color_b", "Color B", "Parameters", 0.0, 1.0, 3.0),
    f32_param!("color_w", "Color W", "Colors", 0.0, 10.0, 4.0),
    f32_param!("accumulation_speed", "Accumulation Speed", "Parameters", 0.0, 1.0, 0.01),
    f32_param!("fade_speed", "Fade Speed", "JFA Parameters", 0.9, 1.0, 0.99),
    f32_param!("freeze_accumulation", "Freeze Accumulation", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("pattern_floor_add", "Pattern Floor Add", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("pattern_temp_add", "Pattern Temp Add", "Parameters", 0.0, 1.0, 0.1),
    f32_param!("pattern_v_offset", "Pattern V Offset", "Parameters", 0.0, 1.0, 0.7),
    f32_param!("pattern_temp_mul1", "Pattern Temp Mul1", "Parameters", 0.0, 1.0, 0.7),
    f32_param!("pattern_temp_mul2_3", "Pattern Temp Mul2 3", "Parameters", 0.0, 1.0, 3.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const KUWAHARA_PARAMS: &[BinParamSpec] = &[
    f32_param!("radius", "Radius", "Filter Parameters", 2.0, 16.0, 5.0),
    f32_param!("q", "Q", "Parameters", 0.0, 1.0, 1.5),
    f32_param!("alpha", "Anisotropy", "Filter Parameters", 0.1, 16.0, 4.0),
    f32_param!("filter_strength", "Filter Strength", "Filter Parameters", 0.0, 16.0, 0.8),
    f32_param!("sigma_d", "Sigma D", "Parameters", 0.0, 1.0, 0.8),
    f32_param!("sigma_r", "Sigma R", "Parameters", 0.0, 1.0, 1.2),
    f32_param!("edge_threshold", "Edge Threshold", "Parameters", 0.0, 1.0, 0.2),
    f32_param!("color_enhance", "Color Filter", "Post-Processing", 0.5, 2.0, 1.0),
    f32_param!("blur_samples", "Samples", "Blur Settings", 5.0, 25.0, 15.0),
    f32_param!("blur_lod", "LOD", "Blur Settings", 0.0, 5.0, 2.0),
    f32_param!("blur_slod", "Step", "Blur Settings", 2.0, 5.0, 4.0),
    f32_param!("lic_length", "Stroke Length", "Brush Strokes (LIC)", 3.0, 40.0, 15.0),
    f32_param!("lic_strength", "Strength", "Brush Strokes (LIC)", 0.0, 1.0, 0.5),
    f32_param!("lic_width", "Stroke Width", "Brush Strokes (LIC)", 0.5, 4.0, 1.5),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const LEGO_PARAMS: &[BinParamSpec] = &[
    f32_param!("brick_scale", "Scale", "Brick Geom", 0.005, 0.05, 0.01),
    f32_param!("lightdir_x", "Dir X", "Lighting", -1.0, 1.0, 0.8),
    f32_param!("lightdir_y", "Dir Y", "Lighting", -1.0, 1.0, 0.6),
    f32_param!("grain", "Grain", "Post-FX", 0.0, 0.1, 0.04),
    f32_param!("gamma", "Gamma", "Post-FX", 0.1, 1.4, 0.4),
    f32_param!("shadow_str", "Shd Str", "Shadows & AO", 0.0, 1.0, 0.5),
    f32_param!("shadow_dist", "Shd Dist", "Shadows & AO", 0.1, 3.0, 1.25),
    f32_param!("ao_str", "AO Cntrst", "Shadows & AO", 0.5, 1.5, 0.85),
    f32_param!("spec_pow", "Spec Pow", "Lighting", 2.0, 50.0, 12.0),
    f32_param!("spec_str", "Spec Str", "Lighting", 0.0, 1.0, 0.3),
    f32_param!("edge_enh", "Edge Enh", "Post-FX", 0.0, 0.5, 0.15),
    f32_param!("stud_h", "Stud H", "Brick Geom", 0.01, 0.1, 0.045),
    f32_param!("base_h", "Base H", "Brick Geom", 0.05, 0.3, 0.2),
    f32_param!("rim_str", "Rim Str", "Lighting", 0.0, 1.0, 0.5),
    f32_param!("res_scale_mult", "Res Scale", "Advanced", 0.01, 2.0, 0.2),
    f32_param!("stud_h_mult", "Stud Mult", "Brick Geom", 1.0, 12.0, 1.0),
    f32_param!("light_r", "Light R", "Parameters", 0.0, 1.0, 0.8),
    f32_param!("light_g", "Light G", "Parameters", 0.0, 1.0, 0.75),
    f32_param!("light_b", "Light B", "Parameters", 0.0, 1.0, 0.7),
    f32_param!("depth_scale", "Depth Scl", "Advanced", 0.5, 1.0, 0.85),
    f32_param!("edge_blend", "Edge Blend", "Post-FX", 0.01, 0.3, 0.3),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const LICH_PARAMS: &[BinParamSpec] = &[
    f32_param!("cloud_density", "Seed", "Lightning Parameters", 0.0, 24.0, 3.0),
    f32_param!("lightning_intensity", "Lightning Intensity", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("branch_count", "Branch", "Lightning Parameters", 0.0, 2.0, 1.0),
    f32_param!("feedback_decay", "Decay", "Lightning Parameters", 0.1, 1.5, 0.98),
    color3_param!("base_color", "Base Color", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color_shift", "Temperature", "Color Settings", 0.1, 20.0, 2.0),
    f32_param!("spectrum_mix", "Spectral", "Color Settings", 0.0, 1.0, 0.5),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const MANDELBULB_PARAMS: &[BinParamSpec] = &[
    f32_param!("power", "Power", "Mandelbulb", 2.0, 12.0, 4.0),
    f32_param!("animation_speed", "Animation Speed", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("hold_duration", "Hold Duration", "Parameters", 0.0, 1.0, 3.0),
    f32_param!("transition_duration", "Transition Duration", "Parameters", 0.0, 1.0, 3.0),
    f32_param!("exposure", "Exposure", "Render", 0.1, 5.0, 1.0),
    f32_param!("focal_length", "Focal Length", "Camera&View", 2.0, 20.0, 2.5),
    f32_param!("dof_strength", "DoF", "Camera&View", 0.0, 1.0, 0.04),
    f32_param!("palette_a_r", "Palette A R", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("palette_a_g", "Palette A G", "Parameters", 0.0, 1.0, 0.7),
    f32_param!("palette_a_b", "Palette A B", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("palette_b_r", "Palette B R", "Parameters", 0.0, 1.0, 0.9),
    f32_param!("palette_b_g", "Palette B G", "Parameters", 0.0, 1.0, 0.8),
    f32_param!("palette_b_b", "Palette B B", "Parameters", 0.0, 1.0, 0.1),
    f32_param!("palette_c_r", "Palette C R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("palette_c_g", "Palette C G", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("palette_c_b", "Palette C B", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("palette_d_r", "Palette D R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("palette_d_g", "Palette D G", "Parameters", 0.0, 1.0, 1.15),
    f32_param!("palette_d_b", "Palette D B", "Parameters", 0.0, 1.0, 0.2),
    f32_param!("gamma", "Gamma", "Render", 0.1, 2.0, 1.1),
    f32_param!("zoom", "Zoom", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("background_r", "Background R", "Parameters", 0.0, 1.0, 0.05),
    f32_param!("background_g", "Background G", "Parameters", 0.0, 1.0, 0.1),
    f32_param!("background_b", "Background B", "Parameters", 0.0, 1.0, 0.15),
    f32_param!("sun_color_r", "Sun Color R", "Parameters", 0.0, 1.0, 8.1),
    f32_param!("sun_color_g", "Sun Color G", "Parameters", 0.0, 1.0, 6.0),
    f32_param!("sun_color_b", "Sun Color B", "Parameters", 0.0, 1.0, 4.2),
    f32_param!("fog_color_r", "Fog Color R", "Parameters", 0.0, 1.0, 0.05),
    f32_param!("fog_color_g", "Fog Color G", "Parameters", 0.0, 1.0, 0.1),
    f32_param!("fog_color_b", "Fog Color B", "Parameters", 0.0, 1.0, 0.15),
    f32_param!("glow_color_r", "Glow Color R", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("glow_color_g", "Glow Color G", "Parameters", 0.0, 1.0, 0.7),
    f32_param!("glow_color_b", "Glow Color B", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("rotation_x", "Rotation X", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("rotation_y", "Rotation Y", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("rotation_z", "Rotation Z", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const MATRIX_PARAMS: &[BinParamSpec] = &[
    f32_param!("red_power", "Red Power", "Matrix Color Settings", 0.5, 3.0, 0.98),
    f32_param!("green_power", "Green Power", "Matrix Color Settings", 0.5, 3.0, 0.85),
    f32_param!("blue_power", "Blue Power", "Matrix Color Settings", 0.5, 3.0, 0.9),
    f32_param!("green_boost", "Green Boost", "Matrix Color Settings", 0.5, 2.0, 1.62),
    f32_param!("contrast", "Contrast", "Matrix Color Settings", 0.5, 2.0, 1.0),
    f32_param!("gamma", "Gamma", "Matrix Color Settings", 0.2, 2.0, 1.0),
    f32_param!("glow", "Glow", "Matrix Color Settings", -1.0, 1.0, 0.05),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const NEBULA_PARAMS: &[BinParamSpec] = &[
    f32_param!("formuparam", "Form Parameter", "Volumetric Parameters", 0.1, 1.0, 0.52),
    f32_param!("stepsize", "Step Size", "Volumetric Parameters", 0.05, 0.5, 0.31),
    f32_param!("zoom", "Zoom", "Volumetric Parameters", 0.1, 112.0, 5.0),
    f32_param!("tile", "Tile", "Volumetric Parameters", 0.1, 3.0, 0.35),
    f32_param!("speed", "Galaxy Speed", "Animation", -0.1, 0.1, 0.02),
    f32_param!("brightness", "Brightness", "Appearance", 0.0001, 0.015, 0.00062),
    f32_param!("dust_intensity", "Dust Intensity", "Appearance", 0.0, 2.0, 1.0),
    f32_param!("distfading", "Distance Fading", "Appearance", 0.1, 3.0, 0.95),
    f32_param!("color_variation", "Color Variation", "Appearance", 0.2, 5.0, 0.51),
    f32_param!("n_boxes", "N Boxes", "Parameters", 0.0, 1.0, 10.0),
    f32_param!("depth", "Depth", "Parameters", 0.0, 1.0, 5.0),
    f32_param!("rotation_x", "Rotation X", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("rotation_y", "Rotation Y", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("scale", "Scale", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("exposure", "Exposure", "Appearance", 0.2, 3.0, 1.6),
    f32_param!("gamma", "Gamma", "Appearance", 0.1, 1.2, 0.4),
    f32_param!("time_scale", "Animation Speed", "Animation", 0.1, 2.0, 1.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const ORBITS_PARAMS: &[BinParamSpec] = &[
    color3_param!("base_color", "Base Color", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("x", "X Position", "Navigation", 0.0, 3.0, 0.5),
    color3_param!("rim_color", "Rim Color", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("y", "Y Position", "Navigation", 0.0, 6.0, 0.5),
    color3_param!("accent_color", "Accent Color", "Parameters", 0.0, 1.0, 0.018),
    f32_param!("gamma_correction", "Gamma", "Rendering", 0.1, 2.0, 0.4),
    f32_param!("travel_speed", "Travel Speed", "Animation", 0.0, 2.0, 1.0),
    f32_param!("col_ext", "Color Extension", "Animation", 0.0, 10.0, 2.0),
    f32_param!("zoom", "Zoom", "Navigation", 0.0001, 1.0, 0.5),
    f32_param!("trap_pow", "Trap Power", "Traps", 0.0, 3.0, 1.0),
    f32_param!("trap_x", "Trap X", "Traps", -5.0, 5.0, -0.5),
    f32_param!("trap_y", "Trap Y", "Traps", -5.0, 5.0, 2.0),
    f32_param!("trap_c1", "Trap Mix", "Traps", 0.0, 1.0, 0.2),
    f32_param!("trap_s1", "Trap Blend", "Traps", 0.0, 2.0, 0.8),
    f32_param!("wave_speed", "Wave Speed", "Animation", 0.0, 2.0, 0.1),
    f32_param!("fold_intensity", "Fold Intensity", "Animation", 0.0, 3.0, 1.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const PATHTRACING_PARAMS: &[BinParamSpec] = &[
    f32_param!("camera_pos_x", "Camera Pos X", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("camera_pos_y", "Camera Pos Y", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("camera_pos_z", "Camera Pos Z", "Parameters", 0.0, 1.0, 6.0),
    f32_param!("camera_target_x", "Camera Target X", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("camera_target_y", "Camera Target Y", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("camera_target_z", "Camera Target Z", "Parameters", 0.0, 1.0, -1.0),
    f32_param!("fov", "Fov", "Parameters", 0.0, 1.0, 40.0),
    f32_param!("aperture", "Depth of Field", "Render Settings", 0.0, 0.5, 0.0),
    f32_param!("rotation_speed", "Animation Speed", "Render Settings", 0.0, 2.0, 0.2),
    f32_param!("exposure", "Exposure", "Render Settings", 0.1, 5.0, 1.5),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const PHYSARUM_PARAMS: &[BinParamSpec] = &[
    f32_param!("sensor_angle", "Sensor Angle", "Agent Physics", 0.05, 1.5, 1.5),
    f32_param!("sensor_dist", "Sensor Distance", "Agent Physics", 1.0, 40.0, 40.0),
    f32_param!("drag", "Momentum", "Agent Physics", 0.0, 0.99, 0.2),
    f32_param!("move_speed", "Speed", "Agent Physics", 0.1, 5.0, 4.95),
    f32_param!("decay_rate", "Decay Rate", "Trail Environment", 0.9, 0.999, 0.999),
    f32_param!("diffuse_rate", "Diffusion Rate", "Trail Environment", 0.0, 1.0, 0.1),
    f32_param!("deposit_amt", "Deposit Amount", "Trail Environment", 1.0, 30.0, 30.0),
    f32_param!("random_jitter", "Random Jitter", "Agent Physics", 0.0, 0.5, 0.5),
    f32_param!("rule_seed", "Rule Seed", "Behavior Rule", 0.0, 100.0, 1.0),
    f32_param!("mutation_scale", "Species Diversity", "Behavior Rule", 0.0, 1.0, 0.3),
    f32_param!("force_scale", "Force Scale", "Behavior Rule", 0.0, 3.0, 0.8),
    f32_param!("sensor_gain", "Sensor Gain", "Behavior Rule", 0.5, 30.0, 5.0),
    f32_param!("species_attract", "Cross-Attraction", "Species Interaction", 0.0, 1.0, 1.0),
    f32_param!("species_repel", "Cross-Repulsion", "Species Interaction", 0.0, 1.0, 0.92),
    f32_param!("strafe_power", "Strafe Power", "Behavior Rule", 0.0, 2.0, 0.15),
    f32_param!("agent_count_scale", "Agent Count Scale", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("glow_intensity", "Glow", "Rendering", 0.0, 2.0, 0.0),
    f32_param!("color_shift", "Color Shift", "Colors", -0.5, 0.5, -0.02),
    f32_param!("specular_strength", "Specular", "Rendering", 0.0, 1.5, 0.25),
    f32_param!("gamma", "Gamma", "Rendering", 0.1, 2.2, 0.5),
    f32_param!("attractor_count", "Count", "Attractors", 0.0, 8.0, 3.0),
    f32_param!("attractor_speed", "Orbit Speed", "Attractors", 0.0, 2.0, 0.3),
    f32_param!("attractor_radius", "Attractor Radius", "Parameters", 0.0, 1.0, 250.0),
    f32_param!("attractor_strength", "Attractor Strength", "Parameters", 0.0, 1.0, 0.15),
    f32_param!("color_spread", "Species Hue Spread", "Colors", 0.0, 1.0, 0.3),
    f32_param!("saturation", "Saturation", "Colors", 0.0, 2.5, 1.58),
    f32_param!("palette_mix", "Palette Mix", "Colors", 0.0, 1.0, 0.57),
    f32_param!("blur_samples", "Feedback Fade", "Rendering", 0.0, 1.0, 0.99),
    f32_param!("color0_r", "Color0 R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color0_g", "Color0 G", "Parameters", 0.0, 1.0, 0.2),
    f32_param!("color0_b", "Color0 B", "Parameters", 0.0, 1.0, 0.2),
    f32_param!("color1_r", "Color1 R", "Parameters", 0.0, 1.0, 0.2),
    f32_param!("color1_g", "Color1 G", "Parameters", 0.0, 1.0, 0.8),
    f32_param!("color1_b", "Color1 B", "Parameters", 0.0, 1.0, 0.3),
    f32_param!("color2_r", "Color2 R", "Parameters", 0.0, 1.0, 0.2),
    f32_param!("color2_g", "Color2 G", "Parameters", 0.0, 1.0, 0.4),
    f32_param!("color2_b", "Color2 B", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("substep", "Substep", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("total_samples", "Total Samples", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("wind_strength", "Slipstream Wind", "Agent Physics", 0.0, 3.0, 0.8),
    f32_param!("turing_scale", "Turing Scale", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("fluid_blend", "Bubble vs Vein Bias", "Agent Physics", 0.0, 2.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const RORSCHACH_PARAMS: &[BinParamSpec] = &[
    f32_param!("seed", "Seed", "Shape", 0.0, 100.0, 87.0),
    f32_param!("zoom", "Zoom", "Shape", 1.0, 10.0, 5.2),
    f32_param!("threshold", "Ink Amount", "Shape", 0.3, 0.6, 0.383),
    f32_param!("distortion", "Warping", "Shape", 0.0, 3.0, 2.63),
    f32_param!("particle_speed", "Brush Speed", "Particle Tracer", 0.0, 5.0, 0.45),
    f32_param!("particle_life", "Trail Life", "Particle Tracer", 0.8, 0.999, 0.99),
    f32_param!("trace_steps", "Density/Steps", "Particle Tracer", 1.0, 100.0, 22.0),
    f32_param!("contrast", "Contrast", "Visual Settings", 0.5, 6.0, 6.0),
    f32_param!("color_r", "Color R", "Parameters", 0.0, 1.0, 0.58),
    f32_param!("color_g", "Color G", "Parameters", 0.0, 1.0, 0.12),
    f32_param!("color_b", "Color B", "Parameters", 0.0, 1.0, 0.12),
    f32_param!("gamma", "Gamma", "Visual Settings", 0.1, 2.0, 0.4),
    f32_param!("style", "Blend", "Visual Settings", 0.0, 1.0, 1.0),
    f32_param!("fbm_octaves", "Detail Octaves", "Shape", 1.0, 25.0, 5.0),
    f32_param!("tint_x", "Tint X", "Parameters", 0.0, 1.0, 0.3),
    f32_param!("tint_y", "Tint Y", "Parameters", 0.0, 1.0, 0.04),
    f32_param!("tint_z", "Tint Z", "Parameters", 0.0, 1.0, 0.28),
    f32_param!("animate", "Animate", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("turbulence", "Turbulence", "Particle Tracer", 0.0, 3.0, 1.2),
    f32_param!("evaporation", "Evaporation", "Particle Tracer", 0.9, 1.0, 1.0),
    f32_param!("light_intensity", "Light Intensity", "Visual Settings", 0.1, 3.0, 1.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const SCENECOLOR_PARAMS: &[BinParamSpec] = &[
    f32_param!("num_segments", "Segments", "Palette Parameters", 1.0, 64.0, 16.0),
    f32_param!("palette_height", "Height", "Palette Parameters", 0.05, 0.5, 0.2),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const SDVERT_PARAMS: &[BinParamSpec] = &[
    f32_param!("lambda", "Vertices", "Geometry", 1.0, 20.0, 3.0),
    f32_param!("theta", "Angle Scale", "Geometry", 0.0, 10.0, 2.0),
    f32_param!("alpha", "Layer Min", "Geometry", 0.001, 0.5, 0.3),
    f32_param!("sigma", "Layer Max", "Geometry", 0.01, 0.5, 0.07),
    f32_param!("gamma", "Layer Size", "Geometry", 0.1, 3.0, 1.5),
    f32_param!("blue", "Hue Shift", "Shape Parameters", 0.0, 5.0, 1.0),
    f32_param!("a", "Depth Factor", "Shape Parameters", 0.0, 5.0, 2.0),
    f32_param!("b", "Fold Pattern", "Shape Parameters", 0.0, 5.0, 0.5),
    f32_param!("base_color_r", "Base Color R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("base_color_g", "Base Color G", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("base_color_b", "Base Color B", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("accent_color_r", "Accent Color R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("accent_color_g", "Accent Color G", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("accent_color_b", "Accent Color B", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("background_r", "Background R", "Parameters", 0.0, 1.0, 0.6),
    f32_param!("background_g", "Background G", "Parameters", 0.0, 1.0, 0.9),
    f32_param!("background_b", "Background B", "Parameters", 0.0, 1.0, 0.9),
    f32_param!("gamma_correction", "Gamma Correction", "Post-Processing", 0.1, 3.0, 0.41),
    f32_param!("aces_tonemapping", "ACES Tonemapping", "Post-Processing", 0.0, 2.0, 0.4),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const SINH_PARAMS: &[BinParamSpec] = &[
    f32_param!("camera_x", "X", "Camera", -1.0, 1.0, 0.1),
    f32_param!("camera_y", "Y", "Camera", 5.0, 20.0, 10.0),
    f32_param!("camera_z", "Z", "Camera", 5.0, 20.0, 10.0),
    f32_param!("orbit_speed", "speed", "Camera", 0.0, 1.0, 0.3),
    f32_param!("magic_number", "Magic Number", "Fractal", 1.0, 100.0, 36.0),
    f32_param!("cv_min", "CV Min", "Fractal", 1.0, 3.0, 2.197),
    f32_param!("cv_max", "CV Max", "Fractal", 2.0, 4.0, 2.99225),
    f32_param!("os_base", "OS Base", "Fractal", 0.00001, 0.001, 0.00004),
    f32_param!("os_scale", "OS Scale", "Fractal", 0.001, 0.1, 0.020401),
    f32_param!("base_color_r", "Base Color R", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("base_color_g", "Base Color G", "Parameters", 0.0, 1.0, 0.25),
    f32_param!("base_color_b", "Base Color B", "Parameters", 0.0, 1.0, 0.05),
    f32_param!("light_color_r", "Light Color R", "Parameters", 0.0, 1.0, 0.8),
    f32_param!("light_color_g", "Light Color G", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("light_color_b", "Light Color B", "Parameters", 0.0, 1.0, 0.3),
    f32_param!("ambient_r", "Ambient R", "Parameters", 0.0, 1.0, 1.2),
    f32_param!("ambient_g", "Ambient G", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("ambient_b", "Ambient B", "Parameters", 0.0, 1.0, 0.8),
    f32_param!("gamma", "Gamma", "Rendering", 0.2, 1.1, 0.4),
    f32_param!("bound", "Bound", "Fractal", 1.0, 25.0, 12.25),
    f32_param!("fractal_scale", "Fractal Scale", "Fractal", 0.01, 1.0, 0.05),
    f32_param!("vignette_offset", "Vignette", "Rendering", 0.0, 1.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const SPIRALCHAOS_PARAMS: &[BinParamSpec] = &[
    f32_param!("a", "Tightness", "Spiral Parameters", 0.0, 3.0, 1.0),
    f32_param!("b", "Speed", "Spiral Parameters", 0.0, 3.0, 1.0),
    f32_param!("c", "N Arms", "Spiral Parameters", 0.0, 3.0, 1.0),
    f32_param!("dof_amount", "Amount", "DOF", 0.0, 3.0, 1.0),
    f32_param!("dof_focal_dist", "Focal Distance", "DOF", 0.0, 3.0, 1.0),
    f32_param!("rotation_x", "X", "Rotation", -1.0, 1.0, 0.0),
    f32_param!("rotation_y", "Y", "Rotation", -1.0, 1.0, 0.0),
    f32_param!("brightness", "Brightness", "Colors", 0.00001, 0.0001, 0.00004),
    f32_param!("color1_r", "Color1 R", "Parameters", 0.0, 1.0, 0.0),
    f32_param!("color1_g", "Color1 G", "Parameters", 0.0, 1.0, 0.7),
    f32_param!("color1_b", "Color1 B", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color2_r", "Color2 R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color2_g", "Color2 G", "Parameters", 0.0, 1.0, 0.3),
    f32_param!("color2_b", "Color2 B", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const SYNTH_PARAMS: &[BinParamSpec] = &[
    f32_param!("tempo", "Tempo", "Playback", 60.0, 180.0, 120.0),
    f32_param!("octave", "Octave", "Playback", 2.0, 7.0, 4.0),
    f32_param!("volume", "Volume", "Playback", 0.0, 1.0, 0.7),
    f32_param!("reverb_mix", "Reverb", "Effects", 0.0, 0.8, 0.15),
    f32_param!("delay_time", "Delay", "Effects", 0.01, 1.0, 0.3),
    f32_param!("delay_feedback", "Feedback", "Effects", 0.0, 0.8, 0.3),
    f32_param!("filter_cutoff", "Cutoff", "Filter", 0.0, 1.0, 0.9),
    f32_param!("filter_resonance", "Resonance", "Filter", 0.0, 0.9, 0.1),
    f32_param!("distortion_amount", "Distortion", "Effects", 0.0, 0.9, 0.0),
    f32_param!("chorus_rate", "Chorus Rate", "Effects", 0.1, 10.0, 2.0),
    f32_param!("chorus_depth", "Chorus Depth", "Effects", 0.0, 0.5, 0.1),
    f32_param!("attack_time", "Attack", "Envelope (ADSR)", 0.001, 0.5, 0.02),
    f32_param!("decay_time", "Decay", "Envelope (ADSR)", 0.01, 1.0, 0.15),
    f32_param!("sustain_level", "Sustain", "Envelope (ADSR)", 0.0, 1.0, 0.7),
    f32_param!("release_time", "Release", "Envelope (ADSR)", 0.01, 2.0, 0.4),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const SYSTEM_PARAMS: &[BinParamSpec] = &[
    f32_param!("a", "Strength", "Field Parameters", 0.0, 2.0, 0.0),
    f32_param!("b", "Gradient", "Field Parameters", 0.0, 1.0, 0.0),
    f32_param!("c", "Scale", "Field Parameters", 0.0, 2.0, 0.4),
    f32_param!("dof_amount", "DOF", "Depth of Field", 0.0, 3.0, 0.0),
    f32_param!("dof_focal_dist", "Focal Distance", "Depth of Field", 0.0, 2.0, 0.96),
    f32_param!("brightness", "Brightness", "Visuals", 0.00001, 0.0002, 0.00004),
    f32_param!("color1_r", "Color1 R", "Parameters", 0.0, 1.0, 0.2),
    f32_param!("color1_g", "Color1 G", "Parameters", 0.0, 1.0, 0.8),
    f32_param!("color1_b", "Color1 B", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color2_r", "Color2 R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color2_g", "Color2 G", "Parameters", 0.0, 1.0, 0.4),
    f32_param!("color2_b", "Color2 B", "Parameters", 0.0, 1.0, 0.1),
    f32_param!("zoom", "Zoom", "Visuals", 0.1, 5.0, 1.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const TAMEIMP_PARAMS: &[BinParamSpec] = &[
    f32_param!("ball_offset_x", "Ball X", "Scene", -1.0, 1.0, 0.5),
    f32_param!("ball_offset_y", "Ball Z", "Scene", -1.0, 1.0, 0.5),
    f32_param!("ball_sink", "Ball Sink", "Scene", -3.2, 3.2, 0.5),
    f32_param!("distortion_amt", "Distortion", "Distortion", 0.0, 75.0, 0.5),
    f32_param!("noise_amt", "Noise Amt", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("stream_width", "Stream Width", "Distortion", 0.01, 0.3, 0.5),
    f32_param!("scale", "Scale", "Scene", 0.3, 3.0, 0.5),
    f32_param!("angle", "Plane Angle", "Scene", -3.14, 3.14, 0.5),
    f32_param!("line_freq", "Line Freq", "Distortion", 20.0, 200.0, 0.5),
    f32_param!("cam_height", "Height", "Cam", 0.5, 5.0, 0.5),
    f32_param!("cam_distance", "Distance", "Cam", 3.0, 10.0, 0.5),
    f32_param!("cam_fov", "FOV", "Cam", 0.5, 2.5, 0.5),
    f32_param!("ball_roughness", "Roughness", "Ball", 0.01, 1.0, 0.5),
    f32_param!("ball_metalness", "Metalness", "Ball", 0.0, 1.0, 0.5),
    f32_param!("gamma", "Gamma", "Post", 0.1, 2.0, 0.5),
    f32_param!("saturation", "Saturation", "Post", 0.0, 2.5, 0.5),
    f32_param!("exposure", "Exposure", "Post", 0.1, 5.0, 0.5),
    f32_param!("contrast", "Contrast", "Post", 0.5, 2.0, 0.5),
    f32_param!("time_offset", "Ball X", "Anim?", 0.0, 50.0, 0.5),
    f32_param!("dof_strength", "Depth of Field", "Cam", 0.0, 0.2, 0.5),
    f32_param!("focal_distance", "Focal Distance", "Cam", 1.0, 10.0, 0.5),
    f32_param!("rotation_x", "Rotation X", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("rotation_y", "Rotation Y", "Parameters", 0.0, 1.0, 0.5),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const TREE_PARAMS: &[BinParamSpec] = &[
    f32_param!("pixel_offset", "Pixel Offset Y", "Fractal Parameters", -3.14, 3.14, 1.35),
    f32_param!("pixel_offset2", "Pixel Offset X", "Fractal Parameters", -3.14, 3.14, 1.0),
    f32_param!("lights", "Lights", "Fractal Parameters", 0.0, 12.2, 2.2),
    f32_param!("exp", "Exp", "Fractal Parameters", 1.0, 120.0, 4.0),
    f32_param!("frame", "Frame", "Visual Settings", 0.0, 2.2, 0.5),
    f32_param!("col1", "Iterations", "Visual Settings", 0.0, 300.0, 205.0),
    f32_param!("col2", "Color 2", "Visual Settings", 0.0, 10.0, 5.5),
    f32_param!("decay", "Feedback", "Visual Settings", 0.0, 1.0, 0.96),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const VERIDISQUO_PARAMS: &[BinParamSpec] = &[
    f32_param!("volume", "Volume", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("tempo_multiplier", "Tempo", "Parameters", 0.5, 2.0, 1.0),
    f32_param!("sample_rate", "Sample Rate", "Parameters", 0.0, 1.0, 0.5),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const VOLUMEPASSAGE_PARAMS: &[BinParamSpec] = &[
    f32_param!("speed", "Speed", "Animation Settings", 0.1, 3.0, 1.0),
    f32_param!("intensity", "Intensity", "Visual Settings", 0.0001, 0.01, 0.001),
    f32_param!("color1_r", "Color1 R", "Parameters", 0.0, 1.0, 0.1),
    f32_param!("color1_g", "Color1 G", "Parameters", 0.0, 1.0, 0.3),
    f32_param!("color1_b", "Color1 B", "Parameters", 0.0, 1.0, 0.7),
    f32_param!("color2_r", "Color2 R", "Parameters", 0.0, 1.0, 0.8),
    f32_param!("color2_g", "Color2 G", "Parameters", 0.0, 1.0, 0.4),
    f32_param!("color2_b", "Color2 B", "Parameters", 0.0, 1.0, 0.2),
    f32_param!("color3_r", "Color3 R", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color3_g", "Color3 G", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("color3_b", "Color3 B", "Parameters", 0.0, 1.0, 1.0),
    f32_param!("gamma", "Gamma", "Visual Settings", 0.1, 3.0, 0.8),
    f32_param!("zoom", "Zoom", "Visual Settings", 0.1, 6.0, 1.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const VORONOI_PARAMS: &[BinParamSpec] = &[
    f32_param!("scale", "Cell Scale", "Pattern", 1.0, 100.0, 24.0),
    f32_param!("offset_value", "Offset", "Pattern", -1.0, 2.0, -1.0),
    f32_param!("cell_index", "Cell Index", "Pattern", 0.0, 3.0, 0.0),
    f32_param!("edge_width", "Edge Width", "Edges", 0.0, 1.0, 0.1),
    f32_param!("highlight", "Highlight", "Edges", 0.0, 15.0, 0.15),
    f32_param!("grain", "Grain", "Post-FX", 0.0, 0.1, 0.04),
    f32_param!("gamma", "Gamma", "Post-FX", 0.1, 1.4, 0.4),
    f32_param!("shadow_str", "Shd Str", "Shadows & AO", 0.0, 1.0, 0.5),
    f32_param!("shadow_dist", "Shd Dist", "Shadows & AO", 0.1, 3.0, 1.25),
    f32_param!("ao_str", "AO Cntrst", "Shadows & AO", 0.5, 1.5, 0.85),
    f32_param!("spec_pow", "Spec Pow", "Lighting", 2.0, 50.0, 12.0),
    f32_param!("spec_str", "Spec Str", "Lighting", 0.0, 1.0, 0.3),
    f32_param!("edge_enh", "Edge Enh", "Edges", 0.0, 0.5, 0.15),
    f32_param!("stud_h", "Stud H", "Cell Geom", 0.0, 0.2, 0.045),
    f32_param!("base_h", "Base H", "Cell Geom", 0.05, 0.3, 0.2),
    f32_param!("rim_str", "Rim Str", "Lighting", 0.0, 1.0, 0.5),
    f32_param!("res_scale_mult", "Res Scale", "Advanced", 0.01, 2.0, 0.2),
    f32_param!("stud_h_mult", "Stud Mult", "Cell Geom", 1.0, 12.0, 1.0),
    f32_param!("lightdir_x", "Dir X", "Lighting", -1.0, 1.0, 0.8),
    f32_param!("lightdir_y", "Dir Y", "Lighting", -1.0, 1.0, 0.6),
    f32_param!("light_r", "Light R", "Parameters", 0.0, 1.0, 0.8),
    f32_param!("light_g", "Light G", "Parameters", 0.0, 1.0, 0.75),
    f32_param!("light_b", "Light B", "Parameters", 0.0, 1.0, 0.7),
    f32_param!("depth_scale", "Depth Scl", "Advanced", 0.5, 1.0, 0.85),
    f32_param!("edge_blend", "Edge Blend", "Edges", 0.01, 0.3, 0.3),
    f32_param!("stud_radius", "Stud Radius", "Cell Geom", 0.05, 0.45, 0.18),
    string_param!("media_path", "Media Path", "Media"),
    action_param!("media_start_webcam", "Start Webcam", "Media"),
    action_param!("media_stop_webcam", "Stop Webcam", "Media"),
    action_param!("video_play", "Video Play", "Media"),
    action_param!("video_pause", "Video Pause", "Media"),
    action_param!("video_restart", "Video Restart", "Media"),
    f32_param!("video_loop", "Video Loop", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_mute", "Video Mute", "Media", 0.0, 1.0, 0.0),
    f32_param!("video_volume", "Video Volume", "Media", 0.0, 1.0, 1.0),
    f32_param!("video_seek", "Video Seek", "Media", 0.0, 3600.0, 0.0),
    f32_param!("control_pause", "Pause", "Transport", 0.0, 1.0, 0.0),
    action_param!("control_reset", "Reset", "Transport"),
    action_param!("control_clear_buffers", "Clear Buffers", "Transport"),
];

pub const BINS: &[&CStr] = &[
    cstr!("roto"),
    cstr!("2dneuron"),
    cstr!("audiovis"),
    cstr!("blockgame"),
    cstr!("buddhabrot"),
    cstr!("cliffordcompute"),
    cstr!("cnn"),
    cstr!("computecolors"),
    cstr!("cuneus"),
    cstr!("debugscreen"),
    cstr!("fft"),
    cstr!("fluid"),
    cstr!("gaussian"),
    cstr!("gaussian3d"),
    cstr!("jfa"),
    cstr!("kuwahara"),
    cstr!("lego"),
    cstr!("lich"),
    cstr!("mandelbulb"),
    cstr!("matrix"),
    cstr!("nebula"),
    cstr!("orbits"),
    cstr!("pathtracing"),
    cstr!("physarum"),
    cstr!("rorschach"),
    cstr!("scenecolor"),
    cstr!("sdvert"),
    cstr!("sinh"),
    cstr!("spiralchaos"),
    cstr!("synth"),
    cstr!("system"),
    cstr!("tameimp"),
    cstr!("tree"),
    cstr!("veridisquo"),
    cstr!("volumepassage"),
    cstr!("voronoi"),
];

pub fn title_for_bin(bin_name: &str) -> Option<&'static CStr> {
    match bin_name {
        "roto" => Some(cstr!("rotation_illusion")),
        "2dneuron" => Some(cstr!("2D Neuron")),
        "audiovis" => Some(cstr!("Audio Visualizer")),
        "blockgame" => Some(cstr!("Block Tower Game")),
        "buddhabrot" => Some(cstr!("Spectral Buddhabrot")),
        "cliffordcompute" => Some(cstr!("Clifford")),
        "cnn" => Some(cstr!("EMNIST")),
        "computecolors" => Some(cstr!("Particle Splatting")),
        "cuneus" => Some(cstr!("cuneus")),
        "debugscreen" => Some(cstr!("Debug Screen")),
        "fft" => Some(cstr!("FFT")),
        "fluid" => Some(cstr!("Fluid Simulation")),
        "gaussian" => Some(cstr!("2D Gaussian Splatting")),
        "gaussian3d" => Some(cstr!("3D Gaussian Splatting")),
        "jfa" => Some(cstr!("JFA")),
        "kuwahara" => Some(cstr!("Kuwahara Filter")),
        "lego" => Some(cstr!("LEGO Effect")),
        "lich" => Some(cstr!("Lich Lightning")),
        "mandelbulb" => Some(cstr!("Mandelbulb Path Tracer")),
        "matrix" => Some(cstr!("matrix")),
        "nebula" => Some(cstr!("universe")),
        "orbits" => Some(cstr!("orbits")),
        "pathtracing" => Some(cstr!("Path Tracer")),
        "physarum" => Some(cstr!("Physarum Engine")),
        "rorschach" => Some(cstr!("Rorschach Tracer")),
        "scenecolor" => Some(cstr!("Scene Color Palette")),
        "sdvert" => Some(cstr!("sdvert")),
        "sinh" => Some(cstr!("Sinh 3D")),
        "spiralchaos" => Some(cstr!("Chaos Spiral")),
        "synth" => Some(cstr!("Synth")),
        "system" => Some(cstr!("Attractor Universe")),
        "tameimp" => Some(cstr!("Currents Path Tracer")),
        "tree" => Some(cstr!("Fractal Tree")),
        "veridisquo" => Some(cstr!("Veridis Quo")),
        "volumepassage" => Some(cstr!("Volume Passage")),
        "voronoi" => Some(cstr!("voronoi")),
        _ => None,
    }
}

pub fn default_dimensions_for_bin(bin_name: &str) -> Option<(u32, u32)> {
    match bin_name {
        "roto" => Some((800, 600)),
        "2dneuron" => Some((600, 800)),
        "audiovis" => Some((800, 600)),
        "blockgame" => Some((600, 800)),
        "buddhabrot" => Some((800, 600)),
        "cliffordcompute" => Some((800, 600)),
        "cnn" => Some((800, 600)),
        "computecolors" => Some((800, 600)),
        "cuneus" => Some((800, 600)),
        "debugscreen" => Some((800, 600)),
        "fft" => Some((800, 600)),
        "fluid" => Some((800, 600)),
        "gaussian" => Some((450, 350)),
        "gaussian3d" => Some((800, 600)),
        "jfa" => Some((800, 600)),
        "kuwahara" => Some((800, 600)),
        "lego" => Some((1280, 720)),
        "lich" => Some((800, 600)),
        "mandelbulb" => Some((600, 400)),
        "matrix" => Some((800, 600)),
        "nebula" => Some((800, 600)),
        "orbits" => Some((800, 600)),
        "pathtracing" => Some((800, 600)),
        "physarum" => Some((1280, 720)),
        "rorschach" => Some((700, 500)),
        "scenecolor" => Some((800, 600)),
        "sdvert" => Some((800, 600)),
        "sinh" => Some((800, 300)),
        "spiralchaos" => Some((800, 600)),
        "synth" => Some((800, 600)),
        "system" => Some((800, 600)),
        "tameimp" => Some((800, 800)),
        "tree" => Some((800, 600)),
        "veridisquo" => Some((800, 600)),
        "volumepassage" => Some((600, 300)),
        "voronoi" => Some((800, 600)),
        _ => None,
    }
}

pub fn params_for_bin(bin_name: &str) -> Option<&'static [BinParamSpec]> {
    match bin_name {
        "roto" => Some(ROTO_PARAMS),
        "2dneuron" => Some(NEURON2D_PARAMS),
        "audiovis" => Some(AUDIOVIS_PARAMS),
        "blockgame" => Some(BLOCKGAME_PARAMS),
        "buddhabrot" => Some(BUDDHABROT_PARAMS),
        "cliffordcompute" => Some(CLIFFORDCOMPUTE_PARAMS),
        "cnn" => Some(CNN_PARAMS),
        "computecolors" => Some(COMPUTECOLORS_PARAMS),
        "cuneus" => Some(CUNEUS_PARAMS),
        "debugscreen" => Some(DEBUGSCREEN_PARAMS),
        "fft" => Some(FFT_PARAMS),
        "fluid" => Some(FLUID_PARAMS),
        "gaussian" => Some(GAUSSIAN_PARAMS),
        "gaussian3d" => Some(GAUSSIAN3D_PARAMS),
        "jfa" => Some(JFA_PARAMS),
        "kuwahara" => Some(KUWAHARA_PARAMS),
        "lego" => Some(LEGO_PARAMS),
        "lich" => Some(LICH_PARAMS),
        "mandelbulb" => Some(MANDELBULB_PARAMS),
        "matrix" => Some(MATRIX_PARAMS),
        "nebula" => Some(NEBULA_PARAMS),
        "orbits" => Some(ORBITS_PARAMS),
        "pathtracing" => Some(PATHTRACING_PARAMS),
        "physarum" => Some(PHYSARUM_PARAMS),
        "rorschach" => Some(RORSCHACH_PARAMS),
        "scenecolor" => Some(SCENECOLOR_PARAMS),
        "sdvert" => Some(SDVERT_PARAMS),
        "sinh" => Some(SINH_PARAMS),
        "spiralchaos" => Some(SPIRALCHAOS_PARAMS),
        "synth" => Some(SYNTH_PARAMS),
        "system" => Some(SYSTEM_PARAMS),
        "tameimp" => Some(TAMEIMP_PARAMS),
        "tree" => Some(TREE_PARAMS),
        "veridisquo" => Some(VERIDISQUO_PARAMS),
        "volumepassage" => Some(VOLUMEPASSAGE_PARAMS),
        "voronoi" => Some(VORONOI_PARAMS),
        _ => None,
    }
}
