// Generated by `cargo run --bin acuneus-gen_registry -- --write`.

pub fn can_run_bin(bin_name: &str) -> bool {
    matches!(
        bin_name,
 "roto" | "2dneuron" | "audiovis" | "blockgame" | "buddhabrot" | "cliffordcompute" | "cnn" | "computecolors" | "cuneus" | "debugscreen" | "fft" | "fluid" | "gaussian" | "gaussian3d" | "jfa" | "kuwahara" | "lego" | "lich" | "mandelbulb" | "matrix" | "nebula" | "orbits" | "pathtracing" | "physarum" | "rorschach" | "scenecolor" | "sdvert" | "sinh" | "spiralchaos" | "synth" | "system" | "tameimp" | "tree" | "veridisquo" | "volumepassage" | "voronoi"
    )
}

pub fn run_bin(bin_name: &str) -> Result<(), Box<dyn std::error::Error>> {
    match bin_name {
        "roto" => roto::run(),
        "2dneuron" => bin_2dneuron::run(),
        "audiovis" => audiovis::run(),
        "blockgame" => blockgame::run(),
        "buddhabrot" => buddhabrot::run(),
        "cliffordcompute" => cliffordcompute::run(),
        "cnn" => cnn::run(),
        "computecolors" => computecolors::run(),
        "cuneus" => cuneus::run(),
        "debugscreen" => debugscreen::run(),
        "fft" => fft::run(),
        "fluid" => fluid::run(),
        "gaussian" => gaussian::run(),
        "gaussian3d" => gaussian3d::run(),
        "jfa" => jfa::run(),
        "kuwahara" => kuwahara::run(),
        "lego" => lego::run(),
        "lich" => lich::run(),
        "mandelbulb" => mandelbulb::run(),
        "matrix" => matrix::run(),
        "nebula" => nebula::run(),
        "orbits" => orbits::run(),
        "pathtracing" => pathtracing::run(),
        "physarum" => physarum::run(),
        "rorschach" => rorschach::run(),
        "scenecolor" => scenecolor::run(),
        "sdvert" => sdvert::run(),
        "sinh" => sinh::run(),
        "spiralchaos" => spiralchaos::run(),
        "synth" => synth::run(),
        "system" => system::run(),
        "tameimp" => tameimp::run(),
        "tree" => tree::run(),
        "veridisquo" => veridisquo::run(),
        "volumepassage" => volumepassage::run(),
        "voronoi" => voronoi::run(),
        _ => Err(format!("embedded cuneus bin is not available: {bin_name}").into()),
    }
}

mod roto {
    include!("../examples/cuneus-roto.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod bin_2dneuron {
    include!("../examples/cuneus-2dneuron.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod audiovis {
    include!("../examples/cuneus-audiovis.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod blockgame {
    include!("../examples/cuneus-blockgame.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod buddhabrot {
    include!("../examples/cuneus-buddhabrot.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod cliffordcompute {
    include!("../examples/cuneus-cliffordcompute.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod cnn {
    include!("../examples/cuneus-cnn.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod computecolors {
    include!("../examples/cuneus-computecolors.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod cuneus {
    include!("../examples/cuneus-cuneus.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod debugscreen {
    include!("../examples/cuneus-debugscreen.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod fft {
    include!("../examples/cuneus-fft.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod fluid {
    include!("../examples/cuneus-fluid.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod gaussian {
    include!("../examples/cuneus-gaussian.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod gaussian3d {
    include!("../examples/cuneus-gaussian3d.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod jfa {
    include!("../examples/cuneus-jfa.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod kuwahara {
    include!("../examples/cuneus-kuwahara.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod lego {
    include!("../examples/cuneus-lego.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod lich {
    include!("../examples/cuneus-lich.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod mandelbulb {
    include!("../examples/cuneus-mandelbulb.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod matrix {
    include!("../examples/cuneus-matrix.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod nebula {
    include!("../examples/cuneus-nebula.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod orbits {
    include!("../examples/cuneus-orbits.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod pathtracing {
    include!("../examples/cuneus-pathtracing.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod physarum {
    include!("../examples/cuneus-physarum.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod rorschach {
    include!("../examples/cuneus-rorschach.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod scenecolor {
    include!("../examples/cuneus-scenecolor.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod sdvert {
    include!("../examples/cuneus-sdvert.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod sinh {
    include!("../examples/cuneus-sinh.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod spiralchaos {
    include!("../examples/cuneus-spiralchaos.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod synth {
    include!("../examples/cuneus-synth.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod system {
    include!("../examples/cuneus-system.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod tameimp {
    include!("../examples/cuneus-tameimp.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod tree {
    include!("../examples/cuneus-tree.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod veridisquo {
    include!("../examples/cuneus-veridisquo.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod volumepassage {
    include!("../examples/cuneus-volumepassage.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

mod voronoi {
    include!("../examples/cuneus-voronoi.rs");

    pub fn run() -> Result<(), Box<dyn std::error::Error>> {
        main()
    }
}

